declare module '@danqing/dq-tokens/dq-mac.css'
declare module '@danqing/dq-tokens/dq-glass.css'
declare module '@danqing/dq-tokens/dq-tauri-macos.css'
declare module '@danqing/dq-ui/style.css'
declare module '@danqing/dq-shell/style.css'
declare module '@danqing/dq-shell'
declare module '@danqing/dq-ui'
